### ISSUE TITLE
Feature request: allow exporting to png/pdf

### ISSUE THREAD

**Issue by gulivan** [azimuttapp/azimutt#287] opened 2024-03-28 09:52 UTC
It would be great to have an option to export the current layout to .pdf or .png

<img width="1029" alt="image" src="https://github.com/azimuttapp/azimutt/assets/34831957/c1f651fc-9534-4906-901b-2d05e41eef8a">

For now I'm using "Capture Node Screenshot" from DevTools but the output image has a low resolution 

![SCR-20240328-lmst-3](https://github.com/azimuttapp/azimutt/assets/34831957/986d2926-6d86-4ff2-9f46-9a96e9153791)

**Comment by loicknuchel** [comment] 2024-05-13 12:28
Hi,
Yeah, clearly it's missing.
But I don't really know how to do it right now and it's not the current focus (trying to get some clients to make it sustainable, that's out top priority now).
It's a duplicate of #251, so I will close this one and we can continue the discussion there ;)

**Closed by loicknuchel** 2024-05-13 12:28 UTC
